openapi: 3.0.3
info:
  title: Inventory Service API
  description: API for inventory management
  version: 1.0.0

paths:
  /v1/inventory/warehouse:
    post:
      tags:
        - warehouse-service
      summary: Get all warehouse
      operationId: getWarehouses
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type : array
                items:
                  $ref: '#/components/schemas/CompactWareHouse'

components:
  schemas:
    CompactWareHouse:
      type: object
      properties:
        code:
          type: string
        name:
          type: string
