spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  server:
    renewal-percent-threshold: 0.5
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 1000
  renewalPercentThreshold: 0.85
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF